language: node_js
node_js: "12"

git:
  depth: false

script:
  - yarn build

deploy:
  - provider: script
    script: if [ "$GH_TOKEN" != "false" ];then npx auto shipit; fi;
    skip-cleanup: true
    on:
      all_branches: true
